# Bridge for the sensor topics
# TODO: Remap more generic, so multi robot simulation is possible, might require https://github.com/gazebosim/ros_gz/pull/754
- ros_topic_name: "scan"
  gz_topic_name: "/model/brum/laser_scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  lazy: true
  direction: GZ_TO_ROS
  # Camera topics: The rest is bridged by ros_gz_image
  # TODO: Make Namespaceable
# NOTE: The camera image is transported by the image bridge?? Maybe not
- ros_topic_name: "center_camera/image_raw"
  gz_topic_name: "/center_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  lazy: true
  direction: GZ_TO_ROS
- ros_topic_name: "center_camera/camera_info"
  gz_topic_name: "/center_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  lazy: true
  direction: GZ_TO_ROS
- ros_topic_name: "io/distance/center/range"
  gz_topic_name: "/model/brum/sonar_scan"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  lazy: true
  direction: GZ_TO_ROS